#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'committer-tools'

trap("SIGINT") { exit 0 }

class Commander
  COMMANDS = {
    'land' => "Ready a Node.js Foundation pull request to be landed"
  }

  def run(command)
    if COMMANDS.keys.include?(command)
      run_command(command)
    else
      run_usage
    end
  end

  private

  def run_command(command)
    github_pr = Preparer.new.run

    if command == 'land'
      LandCommand.new.run(github_pr)
    end
  end

  def run_usage
    puts "Welcome to committer-tools!"

    puts "Available commands:\n"
    COMMANDS.each { |k, v| puts "--> #{k}: #{v}" }
  end
end

Commander.new.run(ARGV.shift)
